pipeline:
  name: test-aspectj
  identifier: testaspectj
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: org.aspectj
        build: <+input>
  stages:
    - stage:
        name: maven
        identifier: maven
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Print tool versions
                  identifier: Print_tool_versions
                  spec:
                    shell: Sh
                    command: |-
                      java -version
                      ./mvnw -B --version
                      ant -version
              - step:
                  type: Run
                  name: Compile package code
                  identifier: Compile_package_code
                  spec:
                    shell: Sh
                    command: ./mvnw -B --file pom.xml -DskipTests install
              - step:
                  type: Plugin
                  name: Attach aspectjrt to build
                  identifier: Attach_aspectjrt_to_build
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: actions/upload-artifact@v3
                      with:
                        name: aspectjrt-java<+matrix.java>
                        path: |
                          aspectjrt/target/aspectjrt-*.jar
                          aspectjrt/target/flattened-pom.xml
              - step:
                  type: Plugin
                  name: Attach aspectjweaver to build
                  identifier: Attach_aspectjweaver_to_build
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: actions/upload-artifact@v3
                      with:
                        name: aspectjrt-java<+matrix.java>
                        path: |
                          aspectjweaver/target/aspectjweaver-*.jar
                          aspectjweaver/target/flattened-pom.xml
              - step:
                  type: Plugin
                  name: Attach aspectjtools to build
                  identifier: Attach_aspectjtools_to_build
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: actions/upload-artifact@v3
                      with:
                        name: aspectjrt-java<+matrix.java>
                        path: |
                          aspectjtools/target/aspectjtools-*.jar
                          aspectjtools/target/flattened-pom.xml
              - step:
                  type: Run
                  name: Create docs
                  identifier: Create_docs
                  spec:
                    shell: Sh
                    command: |
                      ./mvnw -B --file pom.xml -DskipTests process-resources -pl docs -P create-docs
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Plugin
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: GabrielBB/xvfb-action@v1.6
                      with:
                        run: ./mvnw -B --file pom.xml -Daspectj.tests.verbose=false verify
                  when:
                    stageStatus: All
                  failureStrategies: []
        strategy:
          matrix:
            java:
              - 11
              - 17
              - 19
            maxConcurrency: 1
